### ISSUE TITLE
Implement basic user profile scenario

### ISSUE THREAD

**Issue by muzarski** [scylladb/cql-stress#72]
Cassandra-stress lets the users define their own schemas and queries used during the benchmark via `user` command.

It allows the user to define a custom yaml profile file. We should start with supporting the very basic profile yamls, which would consist of the following parameters:
- `keyspace` - name of the stressed keyspace
- `keyspace_definition` - query that creates the keyspace
- `table`
- `table_definition`
- `queries` - a set of queries used during the benchmark. The user can specify the query literal, as well as some details such as (Serial)ConsistencyLevel.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/cql-stress/pull/74
- [ ] https://github.com/scylladb/cql-stress/issues/78
- [ ] https://github.com/scylladb/cql-stress/issues/79
- [ ] https://github.com/scylladb/cql-stress/issues/80
```
